#!/bin/bash

set -e

do_pre_regen() {
  pending_dir=$1

  # Regen ldap conf
  auth_conf_template="/usr/share/yunohost/templates/sympa/ldap.conf"
  auth_conf="${pending_dir}/home/sympa/etc/auth.conf"

  mkdir -p ${pending_dir}/home/sympa/etc/
  cp $auth_conf_template $auth_conf

  domain_list=$(sudo yunohost domain list --output-as plain --quiet)
  main_domain=$(cat /etc/yunohost/current_host)
  ldap_regex=""

  for domain in $domain_list; do
    domain_escape_dots=$(echo $domain | sed 's!\.!\\\.!g')
    ldap_regex="$ldap_regex|.*@$domain_escape_dots"
  done

  # (remove first '|')
  ldap_regex=${ldap_regex#"|"}

  sed -i "s!__DOMAIN_LIST__!$ldap_regex!g" $auth_conf

  # General sympa aliases
  cat << EOF > /etc/mail/sympa_general_aliases
sympa: "| /home/sympa/bin/queue sympa@${main_domain}"
listmaster: "| /home/sympa/bin/queue listmaster@${main_domain}"
bounce+*: "| /home/sympa/bin/bouncequeue sympa@${main_domain}"
abuse-feedback-report: "| /home/sympa/bin/bouncequeue sympa@${main_domain}"
sympa-request: postmaster
sympa-owner: postmaster
EOF
  chown sympa:sympa /etc/mail/sympa_general_aliases

  postalias /etc/mail/sympa_general_aliases


}

do_post_regen() {

  regen_conf_files=$1

  sudo systemctl restart sympa-fcgi.service
  sudo systemctl restart sympa.service
}

FORCE=${2:-0}
DRY_RUN=${3:-0}

case "$1" in
  pre)
    do_pre_regen $4
    ;;
  post)
    do_post_regen $4
    ;;
  *)
    echo "hook called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0

