#!/bin/bash
set -u

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve app settings
APP=$YNH_APP_INSTANCE_NAME
DOMAIN=$(ynh_app_setting_get "$APP" domain)

# FIXME FIXME FIXME
# Add tests that stuff actually exists before removing them

# Remove nginx configuration file
sudo rm -f /etc/nginx/conf.d/$DOMAIN.d/$APP.conf

# Remove systemd services
cd /etc/systemd/system/
systemctl disable sympa.service
systemctl disable sympa-fcgi.service
rm sympa*
systemctl daemon-reload

# Remove home dir / install dir
install_dir="/home/sympa"
rm -rf $install_dir

# Remove mysql table
ynh_mysql_drop_user sympa
ynh_mysql_drop_db sympa

# Reload nginx service
sudo service nginx reload
