#!/bin/bash
set -u

# Source YunoHost helpers
source /usr/share/yunohost/helpers
source future.sh
source common.sh

# Retrieve app settings
APP=$YNH_APP_INSTANCE_NAME
DOMAIN=$(ynh_app_setting_get "$APP" domain)

# FIXME FIXME FIXME
# Add tests that stuff actually exists before removing them

# Remove mysql table
ynh_mysql_drop_user sympa
ynh_mysql_drop_db sympa

# Remove dependencies
ynh_remove_app_dependencies

# Remove CPAN dependencies
# We don't do that because those CPAN module could be used by other software

# Remove nginx configuration file
sudo rm -f /etc/nginx/conf.d/$DOMAIN.d/$APP.conf

# Remove yunohost custom hooks
rm -f /usr/share/yunohost/hooks/conf_regen/98-postfix_sympa
rm -f /usr/share/yunohost/hooks/conf_regen/99-sympa
rm /usr/share/yunohost/templates/sympa/ldap.conf

# Remove aliases files
rm /etc/mail/sympa_*

# Remove sympa services
yunohost service remove sympa

systemctl stop sympa.service
systemctl stop sympa-fcgi.service
systemctl disable sympa.service 2>/dev/null
systemctl disable sympa-fcgi.service 2>/dev/null
rm /etc/systemd/system/sympa*
systemctl daemon-reload

# Remove swap added for Sympa
if [[ ! -z $(mount | grep /tmp | grep tmpfs) ]];
then
    tmp_swap_file=/var/cache/sympa_swapfile
else
    tmp_swap_file=/tmp/sympa_swapfile
fi

sudo swapoff $tmp_swap_file
sudo rm -f $tmp_swap_file

# Remove home dir / install dir
install_dir="/home/sympa"
ynh_secure_remove $install_dir

# Delete system user
ynh_system_user_delete sympa 2>/dev/null

# Reload nginx service
sudo service nginx reload
