#!/bin/bash

# Note: each files and directories you've saved using the ynh_backup helper
# will be located in the current directory, regarding the last argument.

# Exit on command errors and treat unset variables as an error
set -eu

# See comments in install script
app=$YNH_APP_INSTANCE_NAME

# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Retrieve old app settings
domain=$(ynh_app_setting_get "$app" domain)

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path_url}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path_url}"

# Restore sources & data
src_path="/home/sympa/"
sudo cp -a ./sources_and_data "$src_path"

# Restore permissions to app files
# you may need to make some file and/or directory writeable by www-data (nginx user)
sudo chown -R sympa: "$src_path"

# Restore the database
ynh_mysql_execute_file_as_root sympa.dump.sql sympa

# Restore systemd files
sudo cp sympa.services/* /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable sympa.service
sudo systemctl restart sympa.service

# Restore NGINX configuration
sudo cp -a ./nginx.conf "/etc/nginx/conf.d/${domain}.d/${app}.conf"

# Restart webserver
sudo service nginx reload
